config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "todo_items#index"

  resources :todo_items

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  validates :title, presence: true
  # no need to validate description presence, is optional
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController

  def index
    @todoitems = TodoItem.all
  end

  def show
    @todoitem = TodoItem.find(params[:id])
  end

  def new
    @todoitem = TodoItem.new
  end

  def create
    @todoitem = TodoItem.new(todoitem_params)
    if @todoitem.save
      redirect_to @todoitem
    else
      render :new
    end
  end

  def edit
    @todoitem = TodoItem.find(params[:id])
  end

  def update
    @todoitem = TodoItem.find(params[:id])
    if @todoitem.update(todoitem_params)
      redirect_to @todoitem
    else
      render :edit
    end
  end

  def destroy
    @todoitem = TodoItem.find(params[:id])
    @todoitem.destroy
    redirect_to root_path
  end

  private
    def todoitem_params
      params.require(:todo_item).permit(:title, :description)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todo_items/_form.html.erb
<%= form_with model: todoitem do |form| %>

  <div>
    <%= form.label :title %>
    <br>
    <%= form.text_field :title %>
    <%= todoitem.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %>
    <br>
    <%= form.text_area :body %>
    <%= todoitem.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/todo_items/_linktomain.html.erb
<%= link_to "Back to main", todo_items_path %>
<br>

app/views/todo_items/_linktonew.html.erb
<%= link_to "Create a new item", new_todo_item_path %>
<br>

app/views/todo_items/edit.html.erb
<h1>Edit Todo Item</h1>

<%= render "form", todoitem: @todoitem %>

<%= render "linktomain" %>

app/views/todo_items/index.html.erb
<h1>Todo List!</h1>

<ol>
  <% @todoitems.each do |item| %>
    <li>
      <%= link_to item.title, item %>
    </li>
  <% end %>
</ol>

<%= render "linktonew" %>

app/views/todo_items/new.html.erb
<h1>Create a new Todo Item</h1>

<%= render "form", todoitem: @todoitem %>

<%= render "linktomain" %>

app/views/todo_items/show.html.erb
<h1><%= @todoitem.title %></h1>

<p><%= @todoitem.description %></p>

<ul>
  <li>
    <%= link_to "Edit", edit_todo_item_path(@todoitem) %>
  </li>
  <li>
    <%= link_to "Delete", todo_item_path(@todoitem),
                          method: :delete,
                          data: {confirm: "Are you sure?"}
    %>
  </li>
</ul>

<%= render "linktonew" %>
<%= render "linktomain" %>